#spring.application.name=app
#
##Allow overriding port (useful when 8080 is already in use)
#
#server.port=8080
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
#
#spring.datasource.username=postgres
#
#spring.datasource.password=root
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.show-sql=true
#
#spring.jpa.properties.hibernate.format_sql=true
#
## Mail configuration (example using Gmail)
#
#spring.mail.host=smtp.gmail.com
#
#spring.mail.port=587
#
#spring.mail.username =kathiravankathir513@gmail.com
#
#spring.mail.password=lvgcnthnlmtzqyaw
#
#spring.mail.properties.mail.smtp.starttls.enable=true
#
#spring.mail.properties.mail.smtp.starttls.required=true
#
#spring.mail.properties.mail.smtp.auth=true
#
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#
#spring.mail.properties.mail.smtp.timeout =3000
#
#spring.mail.properties.mail.smtp.writetimeout =5000
#
#
#jwt.secret=0cp0fv2T3zQFUF3UcBvUQwgH6hGlsgHgdxJZBXmRJXsOIF/zC2xcntGf5qeAqokVCGeDamR7kIvWdKOwVn8LeQ==
#
#jwt.expiration=86400000
#
#app.frontend-url=http://localhost:5173/


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
jwt.secret=${JWT_SECRET}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.frontend-url=${FRONTEND_URL}
